"""
Database Schemas

Define your MongoDB collection schemas here using Pydantic models.
These schemas are used for data validation in your application.

Each Pydantic model represents a collection in your database.
Model name is converted to lowercase for the collection name:
- User -> "user" collection
- Product -> "product" collection
- BlogPost -> "blogs" collection
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any

# Example schemas (replace with your own):

class User(BaseModel):
    """
    Users collection schema
    Collection name: "user" (lowercase of class name)
    """
    name: str = Field(..., description="Full name")
    email: str = Field(..., description="Email address")
    address: str = Field(..., description="Address")
    age: Optional[int] = Field(None, ge=0, le=120, description="Age in years")
    is_active: bool = Field(True, description="Whether user is active")

class Product(BaseModel):
    """
    Products collection schema
    Collection name: "product" (lowercase of class name)
    """
    title: str = Field(..., description="Product title")
    description: Optional[str] = Field(None, description="Product description")
    price: float = Field(..., ge=0, description="Price in dollars")
    category: str = Field(..., description="Product category")
    in_stock: bool = Field(True, description="Whether product is in stock")

# Add your own schemas here:
# --------------------------------------------------

class Plan(BaseModel):
    """
    Gym workout plans generated by the AI planner
    Collection name: "plan"
    """
    title: str = Field(..., description="Human-friendly plan name")
    name: Optional[str] = Field(None, description="User name (optional)")
    goal: str = Field(..., description="Primary goal e.g., Build Muscle, Lose Fat, Strength, Endurance")
    experience: str = Field(..., description="Experience level e.g., Beginner, Intermediate, Advanced")
    days_per_week: int = Field(..., ge=1, le=7, description="Training days per week")
    duration_weeks: int = Field(..., ge=1, le=52, description="Plan duration in weeks")
    equipment: List[str] = Field(default_factory=list, description="Available equipment")
    focus_areas: List[str] = Field(default_factory=list, description="Body part splits or focus areas")
    constraints: Optional[str] = Field(None, description="Injuries or constraints")
    program: Dict[str, Any] = Field(..., description="Structured program details: weeks -> days -> exercises")
